/* 
 * pagedir.c - CS50 'TSE' common module
 *
 * determine whether the pathname provided as pageDirectory is indeed a directory, and is writable.
 *
 * CS50 
 */
#ifndef __PAGEDIR_H
#define __PAGEDIR_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
//#include <unistd.h>
#include <sys/stat.h>
#include "pagedir.h"


/**************** global types ****************/

/**************** functions ****************/

/**************** dirExists() **************/
/* checks if the directory exists, and if dir exists, check if dir is writable by writing to an empty file
 *
 * Caller provides: 
 *	string directory
 * We return:
 * 	false if dir doesn't exist, or not writable
 * 	true if dir exists and is writable
 * Notes:
 * 	we create a file here caled .crawler, and call fopen()
 */
bool dirExists(char *dir);

/**************** isCrawlerDirectory() **************/
/* checks if the directory has been generated by crawler, and if dir exists, check .crawler file is in there
 *
 * Caller provides: 
 *	string directory
 * We return:
 * 	false if dir doesn't exist, or .crawler does not exist
 * 	true if dir exists and .crawler is readable
 */
bool isCrawlerDirectory(char *dir);

#endif // __PAGEDIR_H
