/* 
 * pagedir.c - CS50 'TSE' common---- module
 *
 * see pagedir.h for more information.
 *
 * CS50 
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
//#include <unistd.h>
#include <sys/stat.h>
#include "pagedir.h"

/**************** file-local global variables ****************/
/* none */

/**************** local types ****************/

/**************** global types ****************/

/**************** global functions ****************/
/* that is, visible outside this file */

/**************** local functions ****************/
/* not visible outside this file */

/**************** dirExists() **************/
// see if the dir exists
bool dirExists(char *dir) 
{
	struct stat s;
	stat(dir, &s);
	if (S_ISDIR(s.st_mode)) {	
		char *file_name = malloc(100*sizeof(char));
		sprintf(file_name, "%s/.crawler", dir);	
		FILE *fp = fopen(file_name, "w");
		if (fp == NULL) {
			fprintf(stderr,"directory %s is not writable.\n", dir);
			return false;
		}
		free(file_name);
		fclose(fp);
		return true;
	}
	fprintf(stderr,"%s is not a directory.\n", dir);
	return false;

}


/**************** isCrawlerDirectory() **************/
// see if the dir has been generated by crawler
bool isCrawlerDirectory(char *dir) 
{
	struct stat s;
        stat(dir, &s);
        if (S_ISDIR(s.st_mode)) {
                char *file_name = malloc(100*sizeof(char));
                sprintf(file_name, "%s/.crawler", dir);
                FILE *fp = fopen(file_name, "r");
                if (fp == NULL) {
                        fprintf(stderr,"directory %s is not a crawled directory.\n", dir);
                        return false;
                }
                free(file_name);
                fclose(fp);
                return true;
        }
	fprintf(stderr,"%s is not a directory.\n", dir);
        return false;
}
